language: android
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-25

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    - extra-android-m2repository

before_script:
    - chmod +x gradlew
#Build, and run tests
script: "./gradlew build testDebugUnitTest"
sudo: false
